# Generated by Django 2.1.7 on 2022-04-15 12:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Salary', models.FloatField()),
                ('Mark', models.FloatField(null=True)),
                ('is_active1', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'shell',
            },
            managers=[
                ('active_field', django.db.models.manager.Manager()),
            ],
        ),
    ]
