# Generated by Django 2.1.7 on 2022-04-15 12:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sons',
            managers=[
                ('active_field1', django.db.models.manager.Manager()),
            ],
        ),
    ]
